// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMnhpCBgWhIjaPFBhI8IAuwuAcgGVAxUQ',
    appId: '1:600231051872:web:8e152064c619c4ab453905',
    messagingSenderId: '600231051872',
    projectId: 'wayanad-gates',
    authDomain: 'wayanad-gates.firebaseapp.com',
    storageBucket: 'wayanad-gates.appspot.com',
    measurementId: 'G-GZB59XLK10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtB8mzQ03gyvfduqCfNyPnMqqqdIIPtOw',
    appId: '1:600231051872:android:4e916a6545eb89fe453905',
    messagingSenderId: '600231051872',
    projectId: 'wayanad-gates',
    storageBucket: 'wayanad-gates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NxIBWyzBNmZjjYMsFmuFkWUN_T6iu1Y',
    appId: '1:600231051872:ios:5f94c163ddecf145453905',
    messagingSenderId: '600231051872',
    projectId: 'wayanad-gates',
    storageBucket: 'wayanad-gates.appspot.com',
    iosBundleId: 'com.example.wayanadGate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NxIBWyzBNmZjjYMsFmuFkWUN_T6iu1Y',
    appId: '1:600231051872:ios:f5666de939b8a641453905',
    messagingSenderId: '600231051872',
    projectId: 'wayanad-gates',
    storageBucket: 'wayanad-gates.appspot.com',
    iosBundleId: 'com.example.wayanadGate.RunnerTests',
  );
}
